services:
  mysql:
    image: mysql:8
    container_name: company-website-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    image: ${DOCKERHUB_USER}/${BACKEND_IMAGE}:${BUILD_TAG}
    container_name: company-website-backend
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    ports:
      - "8082:8000"
    depends_on:
      - mysql

  frontend:
    image: ${DOCKERHUB_USER}/${FRONTEND_IMAGE}:${BUILD_TAG}
    container_name: company-website-frontend
    ports:
      - "8083:80"
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: company-website-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8081:80"
    depends_on:
      - frontend
      - backend

volumes:
  mysql_data:
